### ISSUE TITLE
The main function should return int and not void

### ISSUE THREAD

**Issue by fffelix-jan** [DWN013/C-programs#1]
The C standards specify that the `main()` function should return `int`, not `void`. The function should `return 0;` at the end to indicate that the program ran successfully, or return any other number to indicate an error code. `void main()` is a non-standard main function that some compilers will accept, but technically, you should be using `int main()` and not `void main()`. Thanks!

**Comment by DWN013** [comment]
You are correct. Issue has been resolved, thank you!
